# fly.toml app configuration file generated for bitter-morning-4367 on 2023-07-06T21:33:17-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bitter-morning-4367"
primary_region = "ord"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
